const categorySelectData = {
  wrapperSelector: '#select-wrapper-category',
  name: 'category',
  id: 'category',
  classNames: [''],
  placeholder: 'Выберите рубрику',
  placeholderColor: '#CCCCCC',
  mainColor: '#3D3D3D',
  eventName: 'setCustomSelectValue',
  options: [
    { name: 'Безопасность', value: 'bezopasnost' },
    { name: 'Бизнес-план', value: 'plan' },
    { name: 'Бизнес с нуля', value: 'start' },
    { name: 'Биография', value: 'bio' },
    { name: 'Бухгалтерия', value: 'buhgalteriya' },
    { name: 'Вакансии', value: 'vacancy' },
    { name: 'Вопросы-ответы', value: 'vo' },
    { name: 'Дайджест', value: 'digest' },
    { name: 'Жизнь вне работы', value: 'zvr' },
    { name: 'Новости', value: 'novosti' },
    { name: 'Как есть', value: 'kak-est' },
    { name: 'Календари', value: 'calendars' },
    { name: 'Книги для бизнеса', value: 'knigi' },
    { name: 'Лайфстайл', value: 'lifestyle' },
    { name: 'Личный опыт', value: 'lo' },
    { name: 'Люди в бизнесе', value: 'people' },
    { name: 'Исследования', value: 'research' },
    { name: 'Развитие', value: 'razvitie' },
    { name: 'Сообщество', value: 'blogs' },
    { name: 'Спецпроекты', value: 'specials' },
    { name: 'Тренды', value: 'trendy' },
    { name: 'Шпаргалка', value: 'shpargalka' },
  ],
  isRequired: true,
}